# Permalinks
permalink:           pretty

# Setup
title:               Pang
tagline:             A Metis Data Science Boot Camp Blog
url:                 http://thepang.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Pang Weirich
  url:               http://thepang.github.io
  email:             pang.weirich+github@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/thepang

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
